project:
  type: website

website:
  title: "Time Series Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - intro.qmd
      - ds.qmd
      - dv.qmd
      - explore_analysis.qmd
      - uni_TS_model.qmd
      - multi_TS_model.qmd
      - financial_time_series.qmd
      - dl_time_series.qmd
      - others_analysis.qmd
      - conclusions.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

